=== tulustul/CapitalCasually/public/data/schemas/CapitalMetadata.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "definitions": {
    "CapitalType": {
      "enum": [
        "company",
        "countryBudget",
        "countryDebt",
        "countryIncome"
      ],
      "type": "string"
    }
  },
  "properties": {
    "$schema": {
      "type": "string"
    },
    "datasets": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "description": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "type": {
      "$ref": "#/definitions/CapitalType"
    }
  },
  "required": [
    "$schema",
    "datasets",
    "name",
    "type"
  ],
  "type": "object"
}

=== tulustul/CapitalCasually/public/data/companies/nvidia/metadata.json
{
  "$schema": "../../schemas/CapitalMetadata.schema.json",
  "type": "company",
  "name": "Nvidia",
  "description": "Nvidia Corporation is an American multinational technology company incorporated in Delaware and based in Santa Clara, California. It designs graphics processing units (GPUs) for gaming and professional markets, as well as system on a chip units (SoCs) for the mobile computing and automotive markets.",
  "datasets": ["2025Q1"]
}

=== tulustul/CapitalCasually/public/data/companies/apple/metadata.json
{
  "$schema": "../../schemas/CapitalMetadata.schema.json",
  "type": "company",
  "name": "Apple",
  "description": "Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is one of the Big Five technology companies, alongside Amazon, Alphabet, Microsoft, and Meta.",
  "datasets": ["2025Q2"]
}
